<a href="https://colab.research.google.com/github/dkrumholz/Responsive-personal-portfolio/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
import numpy as np

In [ ]:
torch.__version__

'1.13.1+cu116'

In [ ]:
arr = np.array([1,2,3,4,5])

In [ ]:
print(arr)

[1 2 3 4 5]


In [ ]:
arr.dtype

dtype('int64')

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
x = torch.from_numpy(arr)

In [ ]:
type(x)

torch.Tensor

In [ ]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5])

In [ ]:
x

tensor([1, 2, 3, 4, 5])

In [ ]:
x.dtype

torch.int64

In [ ]:
arr2d = np.arange(0.0,12.0)

In [ ]:
arr2d = arr2d.reshape(4,3)

In [ ]:
x2 = torch.from_numpy(arr2d)

In [ ]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
x

tensor([1, 2, 3, 4, 5])

In [ ]:
arr[0] = 99

In [ ]:
arr

array([99,  2,  3,  4,  5])

In [ ]:
x

tensor([99,  2,  3,  4,  5])

In [ ]:
my_arr = np.arange(0,10)

In [ ]:
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_tensor = torch.tensor(my_arr)

In [ ]:
my_other_tensor = torch.from_numpy(my_arr)

In [ ]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_arr[0] = 9999

In [ ]:
my_arr

array([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [ ]:
my_other_tensor

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [ ]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
new_arr = np.array([1,2,3])

In [ ]:
new_arr.dtype

dtype('int64')

In [ ]:
torch.tensor(new_arr)

tensor([1, 2, 3])

In [ ]:
my_tensor = torch.FloatTensor(new_arr)

In [ ]:
my_tensor.dtype

torch.float32

In [ ]:
torch.empty(4,2)

tensor([[-2.1208e+38,  4.5765e-41],
        [ 1.4743e-34,  0.0000e+00],
        [ 4.4842e-44,  0.0000e+00],
        [ 1.7937e-43,  0.0000e+00]])

In [ ]:
torch.zeros(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [ ]:
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [ ]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [ ]:
my_tensor = torch.tensor([1,2,3])

In [ ]:
my_tensor.dtype

torch.int64

In [ ]:
my_tensor = my_tensor.type(torch.int32)

In [ ]:
my_tensor.dtype

torch.int32

In [ ]:
torch.rand(4,3)

tensor([[0.3466, 0.6863, 0.9816],
        [0.8256, 0.2206, 0.9103],
        [0.4721, 0.0219, 0.6268],
        [0.2916, 0.7433, 0.8619]])

In [ ]:
torch.randn(4,3)

tensor([[ 0.2029,  0.4980,  2.2886],
        [-0.5793, -0.1537,  0.9548],
        [ 0.5943,  0.9446,  0.9703],
        [-0.1596, -0.6828,  1.7607]])

In [ ]:
torch.randint(low=0,high=11,size=(5,5))

tensor([[ 6,  3, 10,  4,  6],
        [ 8,  0, 10,  9,  8],
        [ 9, 10,  9, 10,  7],
        [ 0,  7,  3,  6,  3],
        [ 2,  1,  3,  4,  0]])

In [ ]:
x = torch.zeros(2,5)

In [ ]:
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [ ]:
x.shape

torch.Size([2, 5])

In [ ]:
torch.rand_like(x)

tensor([[0.8464, 0.6822, 0.5022, 0.8323, 0.7295],
        [0.2490, 0.9417, 0.2585, 0.9563, 0.6554]])

In [ ]:
torch.randn_like(x)

tensor([[-0.5602, -1.2129,  0.5692,  1.4386, -1.4115],
        [-0.4264, -0.5204, -0.0126,  1.1210,  0.6541]])

In [ ]:
torch.randint_like(x,low=0,high=11)

tensor([[8., 1., 8., 7., 0.],
        [8., 7., 2., 6., 0.]])

In [ ]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])